curl -X POST https://api.africastalking.com/version1/messaging \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -H "apikey: YOUR_AT_API_KEY" \
  -d "username=YOUR_USERNAME" \
  -d "to=+2547XXXXXXXX" \
  -d "message=Hello world from curl" \
  -d "bulkSMSMode=1"
